model:
  name: primenovo
  checkpoint: weights/model_massive.ckpt

primenovo:
  base_config: external/primenovo/config.yaml
  enable_neptune: false
  load_file_name: weights/model_massive.ckpt

memnovo:
  enabled: true
  residual_scale: 0.005
  apply_to_last_n_layers: 1
  confidence_threshold: null
  target_layers: [-1]
  use_gating: false

inference:
  beam_size: 5
  batch_size: 64
  max_length: 40
  fp16: false
  save_beams: true

evaluation:
  mass_tolerance: 50
  normalize_il: true
